project_id = "lnnsfnztckgouupfestv"

[functions.fetch-content]
verify_jwt = false

[functions.process-content]
verify_jwt = false

[functions.manage-posts]
verify_jwt = false

[functions.manage-sources]
verify_jwt = false

[functions.search-content]
verify_jwt = false

[functions.fetch-twitter-likes]
verify_jwt = false
